from pathlib import Path
import os
from playwright.sync_api import sync_playwright, expect
root=Path(__file__).resolve().parents[1]
art=root/'artifacts';art.mkdir(exist_ok=True)
with sync_playwright() as pw:
 browser_path=os.environ.get('PLAYWRIGHT_CHROMIUM_EXECUTABLE')
 browser=pw.chromium.launch(headless=True,**({'executable_path':browser_path} if browser_path else {}),args=['--enable-unsafe-swiftshader'])
 page=browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
 errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
 page.goto('http://127.0.0.1:5173')
 expect(page.get_by_role('heading',name='Make room for possibilities.')).to_be_visible()
 page.screenshot(path=str(art/'studio.png'),full_page=True)
 page.get_by_role('button',name='Select Master bedroom',exact=True).click()
 expect(page.get_by_label('Room name',exact=True)).to_have_value('Master bedroom')
 page.get_by_label('Room name',exact=True).fill('Primary suite')
 page.get_by_label('Width',exact=True).fill('11')
 expect(page.get_by_text('Primary suite overlaps Passage.',exact=True)).to_be_visible()
 page.get_by_role('button',name='Undo',exact=True).click()
 page.get_by_role('button',name='Select Primary suite',exact=True).click()
 expect(page.get_by_label('Width',exact=True)).to_have_value('10.4')
 page.get_by_label('Room flooring').select_option('terrazzo')
 page.get_by_role('button',name='Rotate bed',exact=True).click()
 page.get_by_label('bed x position').fill('1.5')
 handle=page.get_by_role('button',name='Resize selected room',exact=True)
 handle_box=handle.bounding_box()
 width_before=float(page.get_by_label('Width',exact=True).input_value())
 page.mouse.move(handle_box['x']+handle_box['width']/2,handle_box['y']+handle_box['height']/2)
 page.mouse.down();page.mouse.move(handle_box['x']+handle_box['width']/2+10,handle_box['y']+handle_box['height']/2,steps=5);page.mouse.up()
 assert float(page.get_by_label('Width',exact=True).input_value())>width_before
 page.get_by_role('button',name='Undo',exact=True).click()
 page.get_by_role('button',name='Duplicate this floor',exact=True).click()
 expect(page.get_by_label('Current floor',exact=True)).to_have_value('1')
 page.get_by_role('button',name='Undo',exact=True).click()
 expect(page.get_by_label('Current floor',exact=True)).to_have_value('0')
 page.get_by_role('button',name='Redo',exact=True).click()
 expect(page.get_by_label('Current floor',exact=True)).to_have_value('0')
 expect(page.get_by_label('Current floor',exact=True).locator('option')).to_have_count(2)
 page.reload()
 expect(page.get_by_label('Current floor',exact=True).locator('option')).to_have_count(2)
 page.get_by_role('button',name='Export',exact=True).click()
 with page.expect_download() as event:
  page.get_by_role('button',name='Project JSON',exact=True).click()
 event.value.save_as(str(art/'roundtrip.json'))
 page.get_by_role('button',name='Create a new design',exact=True).click()
 page.get_by_role('button',name='Generate designs',exact=True).click()
 expect(page.locator('.design-option')).to_have_count(3)
 page.screenshot(path=str(art/'options.png'))
 page.locator('.design-option').nth(1).click()
 expect(page.get_by_label('Current floor',exact=True).locator('option')).to_have_count(1)
 page.locator('input[type=file]').set_input_files(str(art/'roundtrip.json'))
 expect(page.get_by_label('Current floor',exact=True).locator('option')).to_have_count(2)
 page.get_by_role('button',name='3D View',exact=True).click()
 expect(page.locator('.viewer canvas')).to_be_visible()
 page.wait_for_timeout(1500)
 page.screenshot(path=str(art/'orbit.png'))
 assert not page.get_by_text('3D needs WebGL',exact=False).count()
 page.get_by_role('button',name='Walkthrough',exact=True).click()
 expect(page.locator('.walk-help')).to_be_visible()
 page.wait_for_timeout(500)
 before=page.locator('.viewer canvas').screenshot()
 page.keyboard.down('w');page.wait_for_timeout(400);page.keyboard.up('w')
 after=page.locator('.viewer canvas').screenshot()
 assert before!=after, 'Walking should change the rendered view'
 page.screenshot(path=str(art/'walk.png'))
 page.get_by_role('button',name='2D Plan',exact=True).click()
 page.get_by_role('button',name='Export',exact=True).click()
 with page.expect_download() as event:
  page.get_by_role('button',name='Floor plan SVG',exact=True).click()
 event.value.save_as(str(art/'floor.svg'))
 assert '<svg' in (art/'floor.svg').read_text()
 page.set_viewport_size({'width':390,'height':844})
 page.screenshot(path=str(art/'mobile.png'),full_page=True)
 assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'), 'Mobile must not overflow horizontally'
 assert not errors,errors
 print('PASS: edit, overlap validation, undo, furniture, materials, floor duplication, reload, generation, JSON import/export, SVG export, WebGL orbit, walkthrough movement, mobile sizing. No page errors.')
 browser.close()
