"""Deterministic UI/render check using a saved, real-model brief re-solved locally."""
import json,os
from pathlib import Path
from playwright.sync_api import sync_playwright,expect
root=Path(__file__).resolve().parents[1];art=root/'artifacts'
fixture=json.loads((art/'studio-fixture.json').read_text())
with sync_playwright() as pw:
 browser=pw.chromium.launch(headless=True,executable_path=os.environ['PLAYWRIGHT_CHROMIUM_EXECUTABLE'],args=['--enable-unsafe-swiftshader'])
 page=browser.new_page(viewport={'width':1440,'height':1000})
 errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
 page.goto('http://127.0.0.1:5173')
 page.evaluate('(c)=>{localStorage.setItem("aangan-fresh-chat-v3","1");localStorage.setItem("aangan-conversation-v3",JSON.stringify(c))}',fixture)
 page.reload()
 page.get_by_label('Current floor',exact=True).select_option('1')
 page.screenshot(path=str(art/'final-first-floor.png'))
 page.get_by_label('Current floor',exact=True).select_option('4')
 page.screenshot(path=str(art/'final-terrace-plan.png'))
 page.get_by_role('button',name='3D view',exact=True).click()
 expect(page.locator('.viewer canvas')).to_be_visible(timeout=20000)
 page.wait_for_timeout(700)
 page.screenshot(path=str(art/'final-house-3d.png'))
 # Regression: changing floors before Walk must not return to the initial terrace.
 page.get_by_label('Current floor',exact=True).select_option('0')
 page.get_by_role('button',name='Walkthrough',exact=True).click()
 expect(page.get_by_label('Current floor',exact=True)).to_have_value('0')
 page.get_by_label('Explore a room',exact=True).select_option(label='Elevator')
 expect(page.get_by_label('Elevator controls')).to_be_visible()
 assert not page.get_by_label('Elevator controls').get_by_role('button',name='Terrace').count()
 page.get_by_label('Elevator controls').get_by_role('button',name='Third',exact=True).click()
 expect(page.get_by_text('Elevator moving…',exact=True)).to_be_visible()
 expect(page.get_by_label('Current floor',exact=True)).to_have_value('3',timeout=15000)
 page.wait_for_function('window.__aangan?.level===3 && Math.abs(window.__aangan.walkerY-30)<.1',timeout=10000)
 page.screenshot(path=str(art/'elevator-third-floor.png'))
 page.get_by_label('Elevator controls').get_by_role('button',name='Ground',exact=True).click()
 expect(page.get_by_label('Current floor',exact=True)).to_have_value('0',timeout=15000)
 page.get_by_label('Current floor',exact=True).select_option('4')
 page.get_by_label('Explore a room',exact=True).select_option(label='Jacuzzi')
 page.wait_for_timeout(500)
 page.screenshot(path=str(art/'terrace-jacuzzi-walk.png'))
 page.get_by_role('button',name='Elevation',exact=True).click()
 expect(page.locator('.studio-elevation svg')).to_be_visible()
 page.screenshot(path=str(art/'final-elevation.png'))
 page.get_by_role('button',name='Floor plan',exact=True).click()
 page.get_by_label('Current floor',exact=True).select_option('1')
 page.get_by_role('button',name='Select Bathroom',exact=True).click()
 page.get_by_label('Room width').fill('2')
 page.get_by_text('Planning decisions & checks',exact=True).click()
 expect(page.get_by_text('Bathroom needs at least',exact=False)).to_be_visible()
 page.get_by_role('button',name='Undo room edit',exact=True).click()
 assert not page.get_by_text('Bathroom needs at least',exact=False).count()
 assert not errors,errors
 print('PASS: updated room allocation, selected-floor walkthrough, elevator G→3→G, terrace jacuzzi, elevations, manual validation and undo',flush=True)
 browser.close()
