from pathlib import Path
import os
from playwright.sync_api import sync_playwright, expect
root=Path(__file__).resolve().parents[1]
art=root/'artifacts';art.mkdir(exist_ok=True)
with sync_playwright() as pw:
 browser=pw.chromium.launch(headless=True,executable_path=os.environ['PLAYWRIGHT_CHROMIUM_EXECUTABLE'],args=['--enable-unsafe-swiftshader'])
 page=browser.new_page(viewport={'width':1440,'height':1000},device_scale_factor=1)
 errors=[];page.on('pageerror',lambda e:(errors.append(str(e)),print('PAGE ERROR:',str(e),flush=True)))
 page.on('console',lambda m:print('CONSOLE:',m.text,flush=True) if m.type=='error' else None)
 page.goto('http://127.0.0.1:5173')
 page.get_by_role('button',name='Walkthrough',exact=True).click()
 page.wait_for_timeout(7000)
 page.screenshot(path=str(art/'debug-start.png'))
 print('VIEW DOM:',page.locator('.viewer').evaluate('(el)=>el.outerHTML.slice(0,600)'),flush=True)
 print('CANVASES:',page.locator('canvas').count(),flush=True)
 expect(page.locator('.viewer canvas')).to_be_visible(timeout=30000)
 expect(page.locator('.tour-room-badge')).to_contain_text('Living room')
 page.get_by_role('button',name='Present design',exact=True).click()
 expect(page.locator('.archviz')).to_have_class('archviz presenting walking')
 page.wait_for_timeout(2500)
 page.screenshot(path=str(art/'interior-day.png'))
 page.get_by_role('button',name='Interior settings',exact=True).click()
 page.get_by_role('button',name='Golden hour',exact=True).click()
 expect(page.get_by_role('button',name='Golden hour',exact=True)).to_have_class('selected')
 page.screenshot(path=str(art/'interior-settings.png'))
 page.get_by_role('button',name='Evening',exact=True).click()
 page.get_by_role('button',name='Close interior settings',exact=True).click()
 page.screenshot(path=str(art/'interior-evening.png'))
 page.get_by_role('button',name='Interior settings',exact=True).click()
 page.get_by_role('button',name='Daylight',exact=True).click()
 page.get_by_role('button',name='Sage & oak',exact=True).click()
 expect(page.get_by_role('button',name='Sage & oak',exact=True)).to_have_class('selected')
 before=page.locator('.tour-minimap g').get_attribute('transform')
 page.locator('.floor-options').get_by_role('button',name='wood',exact=True).click()
 page.wait_for_timeout(1200)
 after=page.locator('.tour-minimap g').get_attribute('transform')
 assert before==after, (before,after)
 page.get_by_role('button',name='Close interior settings',exact=True).click()
 page.get_by_label('Explore a room',exact=True).select_option(label='Master bedroom')
 expect(page.locator('.tour-room-badge')).to_contain_text('Master bedroom')
 page.wait_for_timeout(350)
 page.screenshot(path=str(art/'interior-bedroom.png'))
 page.get_by_label('Explore a room',exact=True).select_option(label='Kitchen')
 expect(page.locator('.tour-room-badge')).to_contain_text('Kitchen')
 page.wait_for_timeout(350)
 page.screenshot(path=str(art/'interior-kitchen.png'))
 page.get_by_role('button',name='Overview',exact=True).click()
 expect(page.locator('.archviz')).to_have_class('archviz presenting orbiting')
 page.wait_for_timeout(350)
 page.screenshot(path=str(art/'interior-overview.png'))
 page.get_by_role('button',name='Walk',exact=True).click()
 expect(page.locator('.archviz')).to_have_class('archviz presenting walking')
 with page.expect_download() as event:page.get_by_role('button',name='Save current view',exact=True).click()
 event.value.save_as(str(art/'presentation-capture.png'))
 assert (art/'presentation-capture.png').stat().st_size>10000
 page.get_by_role('button',name='Mouse look',exact=True).click()
 page.keyboard.press('Escape')
 page.get_by_role('button',name='Exit presentation',exact=True).click()
 expect(page.locator('.archviz')).to_have_class('archviz  walking')
 page.get_by_role('button',name='2D Plan',exact=True).click()
 page.get_by_role('button',name='Select Living room',exact=True).click()
 expect(page.get_by_label('Room flooring')).to_have_value('wood')
 assert not errors,errors
 print('PASS: desktop presentation, interior navigation, moods, palette, saved flooring, stable camera after edit, orbit/walk switch, PNG capture, mouse release, return to editor. No page errors.')
 browser.close()
